config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  devise_for :users 
  
  root 'posts#index'

  namespace :api do
	  namespace :v1 do
	    resources :users, defaults: { format: 'json' }
	  end
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable, :confirmable

	validates :username, uniqueness: true
	validate :username_in_one_word
	validates :username, :format => { with: /\A[a-zA-Z0-9]*\z/ , :message => 'no special characters, only letters and numbers' }
	has_many :posts

	validate :secure_password
	def fullname
		self.first_name + " " + self.last_name
	end

	attr_accessor :login
	def self.find_for_database_authentication warden_conditions
		conditions = warden_conditions.dup
		login = conditions.delete(:login)
		where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
	end

	protected

	# Attempt to find a user by it's email. If a record is found, send new
	# password instructions to it. If not user is found, returns a new user
	# with an email not found error.
	def self.send_reset_password_instructions attributes = {}
		recoverable = find_recoverable_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
		recoverable.send_reset_password_instructions if recoverable.persisted?
		recoverable
	end

	def self.find_recoverable_or_initialize_with_errors required_attributes, attributes, error = :invalid
		(case_insensitive_keys || []).each {|k| attributes[k].try(:downcase!)}

		attributes = attributes.slice(*required_attributes)
		attributes.delete_if {|_key, value| value.blank?}

		if attributes.size == required_attributes.size
			if attributes.key?(:login)
				login = attributes.delete(:login)
				record = find_record(login)
			else
				record = where(attributes).first
			end
		end

	unless record
		record = new

		required_attributes.each do |key|
			value = attributes[key]
			record.send("#{key}=", value)
			record.errors.add(key, value.present? ? error : :blank)
		end
	end
	record
	end

	def self.find_record login
		where(["username = :value OR email = :value", {value: login}]).first
	end

	private

	def username_in_one_word
		if username.to_s.squish.split.size != 1
			errors.add(:username, 'must be one word')
		end
	end
	def secure_password
	    if password.present?
	       if !password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])/) 
	         errors.add :password, "1. Upper Case 2.Lower case 3.Number"
	       end
	    end
	end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ActionController::Base
	respond_to :json
	def index
		@users = User.includes(posts: :comments)
		@response = {:users=> @users}
		respond_with @response, :include => {posts: {only: [:id, :title], :include=>{comments:{only: [:id,:content]}}}}, :except => [:created_at, :updated_at]
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:first_name, :last_name, :username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    @comments = post.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @post = post
    @comment = @post.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = post.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to posts_path, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end

    def post
      Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = current_user.posts.all unless current_user.blank?
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :user_id)
    end
end

app/helpers/api/api_helper.rb
module Api::ApiHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, :class=>"form-control custom-control" , placeholder: "Content", :rows=>4%>

  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-info" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.post.title %></td>
        <td><%= link_to 'Show', comment.post %></td>
        <td><%= link_to 'Edit', edit_post_comment_path(comment.post,comment) %></td>
        <td><%= link_to 'Destroy', comment.post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Comment', new_post_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_base.html.erb
<%unless notice.blank?%>
	<p class="alert alert-info"><%= notice %></p>
<%end%>
<%unless alert.blank?%>
	<p class="alert alert-warning"><%= alert %></p>
<%end%>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.first_name %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
	<div class="">
		 <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	</div>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>KD</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
		    <%= render 'layouts/base' %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, :class=>"form-control" , placeholder: "Title"%>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-info" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <h1>Listing Posts</h1>

      <% @posts.each do |post| %>
        <ul class="list-group outer">
          <li class="list-group-item">Title: <%= post.title %></li>
          <li class="list-group-item">
            <ul class="list-group">
              <% post.comments.each do |comment| %>
                <li class="list-group-item"><%= comment.content%></li>
              <%end%>
            </ul>
          </li>
          <%= link_to 'Show', post %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Comment', new_post_comment_path(post) %>
          
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </ul>
      <% end %>
  <br>

  <%= link_to 'New Post', new_post_path %>
<%end%>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.fullname %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>